version: '3.3'
services:
  keycloak:
      image: jboss/keycloak:16.1.1
      container_name: keycloak
      environment:
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        DB_VENDOR: h2
      volumes:
        - ./keycloak-db:/opt/jboss/keycloak/standalone/data
      ports:
        - 8088:8080